/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package diu.sistemafutbol.Vista;

import java.io.IOException;
import java.awt.Image;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.ImageIcon;

/**
 *
 * @author kevin
 */
public class MenuUsuario extends javax.swing.JFrame {

    /**
     * Creates new form MenuUsuario
     */
    public MenuUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        Escritorio1 = new javax.swing.JDesktopPane();
        jblSiguenos = new javax.swing.JLabel();
        jblSiguenos1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Imag = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        opObtenerDatos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        opMostrar = new javax.swing.JMenuItem();
        opEntrenador = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Usuario");

        Escritorio1.setBackground(new java.awt.Color(2, 41, 123));
        Escritorio1.setForeground(new java.awt.Color(38, 132, 57));
        Escritorio1.setPreferredSize(new java.awt.Dimension(1370, 739));

        jblSiguenos.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jblSiguenos.setForeground(new java.awt.Color(255, 255, 255));
        jblSiguenos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblSiguenos.setText("REDES SOCIALES!");

        jblSiguenos1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jblSiguenos1.setForeground(new java.awt.Color(255, 255, 255));
        jblSiguenos1.setText("!SIGUENOS EN NUESTRAS ");

        jPanel1.setBackground(new java.awt.Color(8, 121, 238));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\kevin\\OneDrive\\Documentos\\NetBeansProjects\\SistemaFutbol\\src\\main\\Imagenes\\Logo_de_Facebook (1).png")); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jLabel3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel3KeyPressed(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 55, -1));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FACEBOOK");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 160, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\kevin\\OneDrive\\Documentos\\NetBeansProjects\\SistemaFutbol\\src\\main\\Imagenes\\Imbabura.png")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 100)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("IMBABURA S.C.");
        jLabel4.setToolTipText("");

        Imag.setPreferredSize(new java.awt.Dimension(500, 500));

        Escritorio1.setLayer(jblSiguenos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio1.setLayer(jblSiguenos1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio1.setLayer(Imag, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout Escritorio1Layout = new javax.swing.GroupLayout(Escritorio1);
        Escritorio1.setLayout(Escritorio1Layout);
        Escritorio1Layout.setHorizontalGroup(
            Escritorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Escritorio1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(Escritorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Escritorio1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Escritorio1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Imag, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(Escritorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Escritorio1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addComponent(jblSiguenos, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Escritorio1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jblSiguenos1)))
                .addGap(22, 22, 22))
        );
        Escritorio1Layout.setVerticalGroup(
            Escritorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Escritorio1Layout.createSequentialGroup()
                .addGroup(Escritorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Escritorio1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(Escritorio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Imag, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Escritorio1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jblSiguenos1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jblSiguenos)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        Escritorio.setLayer(Escritorio1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addComponent(Escritorio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio1, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
        );

        jMenu1.setText("Estudiantes");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Ver Estudiantes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        opObtenerDatos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opObtenerDatos.setText("Obtener Datos del Estudiante");
        opObtenerDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opObtenerDatosActionPerformed(evt);
            }
        });
        jMenu1.add(opObtenerDatos);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Entrenador");

        opMostrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opMostrar.setText("Mostrar Entrenador");
        opMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opMostrarActionPerformed(evt);
            }
        });
        jMenu2.add(opMostrar);

        opEntrenador.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opEntrenador.setText("Informacion del Entrenador");
        opEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opEntrenadorActionPerformed(evt);
            }
        });
        jMenu2.add(opEntrenador);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        VerEstudianteUsuario mu = new VerEstudianteUsuario();
        Escritorio.add(mu);
        mu.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void opMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opMostrarActionPerformed
        MostarEntrenadorUsuario meu = new MostarEntrenadorUsuario();
        Escritorio.add(meu);
        meu.show();
    }//GEN-LAST:event_opMostrarActionPerformed

    private void opObtenerDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opObtenerDatosActionPerformed
        BuscadorEstudianteUsuario beu = new BuscadorEstudianteUsuario();
        Escritorio.add(beu);
        beu.show();
    }//GEN-LAST:event_opObtenerDatosActionPerformed

    private void opEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opEntrenadorActionPerformed
        buscadorEntrenadorUsuario beu = new buscadorEntrenadorUsuario();
        Escritorio.add(beu);
        beu.show();
    }//GEN-LAST:event_opEntrenadorActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        if (java.awt.Desktop.isDesktopSupported()) {
            java.awt.Desktop desktop = java.awt.Desktop.getDesktop();
            if (desktop.isSupported(java.awt.Desktop.Action.BROWSE)) {
                try {

                    java.net.URI uri = new java.net.URI("https://www.facebook.com/p/Escuela-Formativa-Imbabura-SC-100083222566266/");
                    desktop.browse(uri);
                } catch (IOException | URISyntaxException e) {
                    System.out.println(e);
                }
            }
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel3KeyPressed

    }//GEN-LAST:event_jLabel3KeyPressed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        if (java.awt.Desktop.isDesktopSupported()) {
            java.awt.Desktop desktop = java.awt.Desktop.getDesktop();
            if (desktop.isSupported(java.awt.Desktop.Action.BROWSE)) {
                try {

                    java.net.URI uri = new java.net.URI("https://www.facebook.com/p/Escuela-Formativa-Imbabura-SC-100083222566266/");
                    desktop.browse(uri);
                } catch (IOException | URISyntaxException e) {
                    System.out.println(e);
                }
            }
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUsuario().setVisible(true);
            }
        });
    }
    public static int contador = 1;

    public static void mostrarImagenes(String name) {
        Image imagenes = new ImageIcon(name).getImage();
        ImageIcon imagen = new ImageIcon(imagenes.getScaledInstance(900, 500, Image.SCALE_SMOOTH));
        Imag.setIcon(imagen);

    }

    public static void Tiempo(int minutos, int segundos) {
        Timer timer = new Timer();

        TimerTask task = new TimerTask() {
            @Override
            public void run() {
                System.out.println("Han pasado 10 segundos");

                if (contador == 10) {
                    contador = 1; // Reinicia el contador
                } else {
                    contador++; // Aumenta el contador
                }

                mostrarImagenes("C:\\Users\\kevin\\OneDrive\\Documentos\\NetBeansProjects\\SistemaFutbol\\src\\main\\Imagenes\\" + contador + ".jpg");
            }
        };

        long intervalo = segundos * 1000; // Convierte segundos a milisegundos

        timer.schedule(task, intervalo, intervalo); // Ejecuta el TimerTask cada 10 segundos
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    public static javax.swing.JDesktopPane Escritorio1;
    public static javax.swing.JLabel Imag;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jblSiguenos;
    private javax.swing.JLabel jblSiguenos1;
    private javax.swing.JMenuItem opEntrenador;
    private javax.swing.JMenuItem opMostrar;
    private javax.swing.JMenuItem opObtenerDatos;
    // End of variables declaration//GEN-END:variables
}
